### ISSUE TITLE
how to run the project

### ISSUE THREAD

**Issue by nextshubham** [leota/MEAN-stack-authentication#1]
can you please tell step by step how to run this project.
like
1.
2.
3.

**Comment by leota** [comment]
Hi @nextshubham 

it is explained here: 
https://github.com/leota/MEAN-stack-authentication/blob/master/README.md

**Comment by nextshubham** [comment]
hi i executed the project successfully ,but i think you set user as the default user so until and unless we change the role in database we can not see the admin view .i think you should add an option during register to select role also so  anyone can see that users list page also.

**Comment by nextshubham** [comment]
i am a new learner in angular and node ,thats why i am searching for how people code and  try to understand there code.

**Comment by leota** [comment]
> i think you set user as the default user so until and unless we change the role in database we can not see the admin view .i think you should add an option during register to select role also so anyone can see that users list page also.

@nextshubham Yes at the moment the only way to set user role as "admin" is changing it into the DB. Reason is that usually when you register to a website you can't choose to be admin ;)
But I see your point. Being this just a demo it could be added as an option
